### ISSUE TITLE
Problem with noscript tag

### ISSUE THREAD

**Issue by da-yauhenzadziarkouski** [JPeer264/node-rcs-core#134]
**The problem:**
It's a bit odd, but class names aren't replaced when the html code is wrapped in **noscript** tag ```<noscript>...</noscript>```.

**Example output:**
```
<p class="nh nb nl">Some text goes here</p>

<noscript><p class="text-h2 text-gray-800 font-heading">Some text goes here</p></noscript>
```

Thank you @JPeer264 for the hard work on RCS, btw!

**Comment by JPeer264** [comment]
Could have waited with the release from the other ticket. But it is available with v`3.6.3`

**Comment by da-yauhenzadziarkouski** [comment]
Thanks a lot @JPeer264 for the blazing-fast updates!

Somehow, version 3.6.3 throws an error in my setup:
```
[build:eleventy] Writing _site/index.html from ./src/index.njk.
[build:eleventy] Problem writing Eleventy templates: (more in DEBUG output)
[build:eleventy] > Expected corresponding JSX closing tag for <img>
[build:eleventy] 
[build:eleventy] `SyntaxError` was thrown:
[build:eleventy]     SyntaxError: Expected corresponding JSX closing tag for <img>
[build:eleventy]         at Espree.raise (/Users/yauhen/projects/eleventy/node_modules/espree/lib/espree.js:190:25)
[build:eleventy]         at Espree.jsx_parseElementAt (/Users/yauhen/projects/eleventy/node_modules/acorn-jsx/index.js:407:16)
[build:eleventy]         at Espree.jsx_parseElementAt (/Users/yauhen/projects/eleventy/node_modules/acorn-jsx/index.js:391:32)
[build:eleventy]         at Espree.jsx_parseElementAt (/Users/yauhen/projects/eleventy/node_modules/acorn-jsx/index.js:391:32)
[build:eleventy]         at Espree.jsx_parseElementAt (/Users/yauhen/projects/eleventy/node_modules/acorn-jsx/index.js:391:32)
[build:eleventy]         at Espree.jsx_parseElement (/Users/yauhen/projects/eleventy/node_modules/acorn-jsx/index.js:436:19)
[build:eleventy]         at Espree.parseExprAtom (/Users/yauhen/projects/eleventy/node_modules/acorn-jsx/index.js:443:21)
[build:eleventy]         at Espree.pp$3.parseExprSubscripts (/Users/yauhen/projects/eleventy/node_modules/acorn/dist/acorn.js:2129:21)
[build:eleventy]         at Espree.pp$3.parseMaybeUnary (/Users/yauhen/projects/eleventy/node_modules/acorn/dist/acorn.js:2106:19)
[build:eleventy]         at Espree.pp$3.parseExprOps (/Users/yauhen/projects/eleventy/node_modules/acorn/dist/acorn.js:2041:21)
[build:eleventy] Copied 10 files / Wrote 2 files in 1.36 seconds (v0.12.1)
[build:eleventy] npm ERR! code ELIFECYCLE
[build:eleventy] npm ERR! errno 1
[build:eleventy] npm ERR! eleventy@ build:eleventy: `eleventy`
[build:eleventy] npm ERR! Exit status 1
[build:eleventy] npm ERR! 
[build:eleventy] npm ERR! Failed at the eleventy@ build:eleventy script.
[build:eleventy] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
I've tried to dig in the RCS code with no luck :)
Version **3.6.2** works perfectly, btw.

Thanks again!

**Comment by JPeer264** [comment]
Where do you have that `img` tag? Is it inside the `<noscript>` attribute?

**Comment by da-yauhenzadziarkouski** [comment]
Wow! Thanks a ton, sir! 3.6.4 works like a charm! Have a great weekend :)

**Comment by JPeer264** [comment]
Thanks you too :)
