### ISSUE TITLE
escodegen is not in dependencies

### ISSUE THREAD

**Issue by klimashkin** [JPeer264/node-rcs-core#19]
```
Error: Cannot find module 'escodegen'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/~/rcs-core/lib/options/replace.js:8:19)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/~/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

**Comment by JPeer264** [comment]
Wow, how could that happen. The weird think is that it also passed my CI. Obviously I relied too much on my not-yet-existed linting. I fix this ASAP, sorry for that happening.
